LANGUAGES = {
    'ru': {
        'start_welcome': '👋 Добро пожаловать в систему поддержки!\n\nВыберите действие в меню ниже.',
        'new_ticket_button': '📩 Новая заявка',
        'my_tickets_button': '🎫 Мои заявки',
        'cancel_button': '❌ Отмена',
        'back_button': '🔙 Назад',
        'ask_for_ticket_text': '✏️ Пожалуйста, опишите суть вашей заявки.',
        'ask_priority': '🔻 Выберите приоритет заявки:',
        'ask_category': '📂 Выберите категорию заявки:',
        'ticket_text_received': '✅ Текст заявки получен.',
        'ticket_created_info': '🆕 Заявка *{code}* создана.\nСоздано: {created_at}\nСтатус: {status}',
        'your_tickets_title': '🎫 Ваши заявки:',
        'ticket_detail_title': '🔍 Детали заявки {code}',
        'ticket_text': '✏️ Текст: {text}',
        'ticket_created_at': '📅 Создано: {created}',
        'ticket_status': '📌 Статус: {status}',
        'ticket_user': '👤 Пользователь: {user}',
        'ticket_priority': '⚠️ Приоритет: {priority}',
        'ticket_category': '📂 Категория: {category}',
        'ticket_closed_success': '✅ Заявка {code} успешно закрыта.',
        'ticket_not_open_for_reply': '❌ Нельзя ответить на закрытую заявку.',
        'reply_message_prompt': '💬 Введите сообщение для заявки {code}:',
        'message_sent_to_user': '✅ Сообщение отправлено пользователю.',
        'choose_language': '🌐 Выберите язык:',
        'language_set': '✅ Язык изменен.',
        'no_access': '❌ У вас нет доступа.',
        'view_all_tickets_button': '📋 Все заявки',
        'ticket_status_open': 'Открыта',
        'ticket_status_closed': 'Закрыта',
        'ticket_priority_low': 'Низкий',
        'ticket_priority_medium': 'Средний',
        'ticket_priority_high': 'Высокий',
        'ticket_category_general': 'Общий вопрос',
        'ticket_category_technical': 'Техническая проблема',
        'ticket_category_financial': 'Финансовый вопрос',
        'export_status_all': 'Все',
        'export_start_date': '📅 Начальная дата',
        'export_end_date': '📅 Конечная дата',
        'export_file_generated': '✅ Файл экспорта сгенерирован.',
        'thanks_for_feedback': '🙏 Спасибо за ваш отзыв!',
        'ask_feedback_text': '✏️ Пожалуйста, оставьте текстовый отзыв.',
        'feedback_prompt': '⭐ Пожалуйста, оцените качество решения заявки {code}.',
        'no_tickets_found': '❌ Заявки не найдены.',
        'unassigned_tickets': 'Не назначена',
        'ticket_assigned': '👤 Назначено: {assigned}',
        'ticket_assigned_success': '✅ Заявка {code} назначена {username}.',
        'ticket_unassigned_success': '✅ Назначение заявки {code} снято.',
        'edit_ticket_menu_title': '✏️ Редактирование заявки {code}',
        'edit_text_button': '📝 Изменить текст',
        'edit_priority_button': '⚠️ Изменить приоритет',
        'edit_category_button': '📂 Изменить категорию',
        'enter_new_ticket_text': '✏️ Введите новый текст заявки:',
        'select_new_priority': '⚠️ Выберите новый приоритет:',
        'select_new_category': '📂 Выберите новую категорию:',
        'ticket_updated_success': '✅ Заявка {code} успешно обновлена.',
        'no_changes_made': 'ℹ️ Изменений не внесено.',
        'invalid_date_format': '❌ Неверный формат даты. Используйте YYYY-MM-DD.',
        'back_to_main_user_menu': '↩️ Возврат в главное меню пользователя.',
        'select_filter': '⚙️ Выберите фильтр:',
        'no_admins_or_moderators': '❌ Нет доступных администраторов или модераторов для назначения.',
        'select_admin_to_assign': '👥 Выберите администратора/модератора для назначения заявки {code}:',
        'stale_tickets_title': '⏳ Зависшие заявки (нет ответа более 24 часов):',
        'ticket_details_not_found': '❌ Детали заявки не найдены.',
        'ticket_rating': '⭐ Рейтинг: {rating}',
        'ticket_feedback': '💬 Отзыв: {feedback}',
        'last_reply_at': '🕒 Последний ответ админа: {timestamp}',
        'no_last_reply': '🕒 Последний ответ админа: Нет',
        'response_templates_button': '📝 Шаблоны ответов',
        'create_template_button': '➕ Создать шаблон',
        'view_templates_button': '📄 Просмотреть шаблоны',
        'delete_template_button': '🗑️ Удалить шаблон',
        'ask_template_name': '✍️ Введите название для нового шаблона:',
        'ask_template_text': '💬 Введите текст шаблона:',
        'template_added_success': '✅ Шаблон "{name}" успешно добавлен.',
        'template_name_exists': '❌ Шаблон с таким именем уже существует.',
        'no_templates': 'ℹ️ Шаблоны не найдены.',
        'templates_list_title': '📄 Список шаблонов ответов:',
        'select_template_to_delete': '🗑️ Выберите шаблон для удаления:',
        'confirm_delete_template': '❓ Вы уверены, что хотите удалить шаблон "{name}"?',
        'template_not_found': '❌ Шаблон не найден.',
        'template_deleted_success': '✅ Шаблон успешно удален.',
        'yes_button': '✅ Да',
        'no_button': '❌ Нет',
        'unassign_ticket_button': '🚫 Снять назначение',
        'back_to_ticket_detail': '🔙 К деталям заявки',
        'ticket_not_open_for_edit': '❌ Эту заявку нельзя редактировать. Возможно, она закрыта или уже назначена.',
        'ticket_code_not_found': '❌ Заявка с кодом {code} не найдена.',
        'not_your_ticket': '❌ Это не ваша заявка.',
        'role_user': 'Пользователь',
        'role_admin': 'Админ',
        'role_moderator': 'Модератор',
        'role_superadmin': 'Супер-админ',
        'admin_menu_title': '⚙️ Панель администратора',
        'moderator_menu_title': '⚙️ Панель модератора',
        'superadmin_menu_title': '👑 Панель супер-администратора',
        'admin_panel_button': '⚙️ Админ-панель',
        'moderator_panel_button': '⚙️ Модератор-панель',
        'superadmin_panel_button': '👑 Супер-админ-панель',
        'language_button': '🌐 Язык',
        'manage_users_title': '👥 Управление пользователями',
        'no_users_registered': '❌ Зарегистрированные пользователи не найдены.',
        'set_role_for_user': 'Изменить роль для {user_display}:',
        'role_updated_success': '✅ Роль пользователя {user_display} обновлена до "{role}".',
        'assign_ticket_button': '👤 Назначить',
        'send_template_button': '📝 Отправить шаблон',
        'reply_button': '💬 Ответить',
        'close_ticket_button': '🔒 Закрыть заявку',
        'edit_ticket_button': '✏️ Редактировать',
        'ticket_code_not_found_in_state': 'Ошибка: Код заявки не найден в состоянии.',
        'ticket_already_closed': 'ℹ️ Заявка {code} уже закрыта.',
        'feedback_data_not_found': 'Ошибка: не удалось найти данные для отзыва.',
        'ticket_code_not_found_for_edit': 'Ошибка: Код заявки для редактирования не найден.',
        'export_options_title': '📊 Опции экспорта',
        'export_priority_all': 'Все приоритеты',
        'export_category_all': 'Все категории',
        'export_assigned_all': 'Все назначенные',
        'export_assigned_unassigned': 'Не назначенные',
        'export_assigned_me': 'Назначенные мне',
        'export_assigned_specific': 'Назначить конкретному',
        'export_tickets_button': '✅ Экспортировать заявки',
        'export_enter_dates': 'Введите дату в формате ГГГГ-ММ-ДД (оставьте пустым для сброса фильтра).',
        'select_filter_status': 'Выберите статус для фильтрации:',
        'select_filter_priority': 'Выберите приоритет для фильтрации:',
        'select_filter_category': 'Выберите категорию для фильтрации:',
        'select_filter_assigned': 'Выберите назначение для фильтрации:',


    },

    'en': {
        'start_welcome': '👋 Welcome to the support system!\n\nPlease choose an action from the menu below.',
        'new_ticket_button': '📩 New Ticket',
        'my_tickets_button': '🎫 My Tickets',
        'cancel_button': '❌ Cancel',
        'back_button': '🔙 Back',
        'ask_for_ticket_text': '✏️ Please describe your issue.',
        'ask_priority': '🔻 Choose ticket priority:',
        'ask_category': '📂 Choose ticket category:',
        'ticket_text_received': '✅ Ticket text received.',
        'ticket_created_info': '🆕 Ticket *{code}* created.\nCreated at: {created_at}\nStatus: {status}',
        'your_tickets_title': '🎫 Your tickets:',
        'ticket_detail_title': '🔍 Ticket details {code}',
        'ticket_text': '✏️ Text: {text}',
        'ticket_created_at': '📅 Created at: {created}',
        'ticket_status': '📌 Status: {status}',
        'ticket_user': '👤 User: {user}',
        'ticket_priority': '⚠️ Priority: {priority}',
        'ticket_category': '📂 Category: {category}',
        'ticket_closed_success': '✅ Ticket {code} successfully closed.',
        'ticket_not_open_for_reply': '❌ Cannot reply to a closed ticket.',
        'reply_message_prompt': '💬 Enter your message for ticket {code}:',
        'message_sent_to_user': '✅ Message sent to user.',
        'choose_language': '🌐 Choose your language:',
        'language_set': '✅ Language changed.',
        'no_access': '❌ You do not have access.',
        'view_all_tickets_button': '📋 All tickets',
        'ticket_status_open': 'Open',
        'ticket_status_closed': 'Closed',
        'ticket_priority_low': 'Low',
        'ticket_priority_medium': 'Medium',
        'ticket_priority_high': 'High',
        'ticket_category_general': 'General question',
        'ticket_category_technical': 'Technical issue',
        'ticket_category_financial': 'Financial issue',
        'export_status_all': 'All',
        'export_start_date': '📅 Start date',
        'export_end_date': '📅 End date',
        'export_file_generated': '✅ Export file generated.',
        'thanks_for_feedback': '🙏 Thank you for your feedback!',
        'ask_feedback_text': '✏️ Please leave your textual feedback.',
        'feedback_prompt': '⭐ Please rate the resolution quality for ticket {code}.',
        'no_tickets_found': '❌ No tickets found.',
        'unassigned_tickets': 'Unassigned',
        'ticket_assigned': '👤 Assigned to: {assigned}',
        'ticket_assigned_success': '✅ Ticket {code} assigned to {username}.',
        'ticket_unassigned_success': '✅ Ticket {code} unassigned.',
        'edit_ticket_menu_title': '✏️ Editing ticket {code}',
        'edit_text_button': '📝 Edit text',
        'edit_priority_button': '⚠️ Edit priority',
        'edit_category_button': '📂 Edit category',
        'enter_new_ticket_text': '✏️ Enter new ticket text:',
        'select_new_priority': '⚠️ Choose new priority:',
        'select_new_category': '📂 Choose new category:',
        'ticket_updated_success': '✅ Ticket {code} successfully updated.',
        'no_changes_made': 'ℹ️ No changes made.',
        'invalid_date_format': '❌ Invalid date format. Use YYYY-MM-DD.',
        'back_to_main_user_menu': '↩️ Return to main user menu.',
        'select_filter': '⚙️ Select filter:',
        'no_admins_or_moderators': '❌ No administrators or moderators available for assignment.',
        'select_admin_to_assign': '👥 Select an admin/moderator to assign ticket {code}:',
        'stale_tickets_title': '⏳ Stale Tickets (no reply for over 24 hours):',
        'ticket_details_not_found': '❌ Ticket details not found.',
        'ticket_rating': '⭐ Rating: {rating}',
        'ticket_feedback': '💬 Feedback: {feedback}',
        'last_reply_at': '🕒 Last admin reply: {timestamp}',
        'no_last_reply': '🕒 Last admin reply: None',
        'response_templates_button': '📝 Response Templates',
        'create_template_button': '➕ Create Template',
        'view_templates_button': '📄 View Templates',
        'delete_template_button': '🗑️ Delete Template',
        'ask_template_name': '✍️ Enter a name for the new template:',
        'ask_template_text': '💬 Enter the template text:',
        'template_added_success': '✅ Template "{name}" successfully added.',
        'template_name_exists': '❌ Template with this name already exists.',
        'no_templates': 'ℹ️ No templates found.',
        'templates_list_title': '📄 List of Response Templates:',
        'select_template_to_delete': '🗑️ Select template to delete:',
        'confirm_delete_template': '❓ Are you sure you want to delete template "{name}"?',
        'template_not_found': '❌ Template not found.',
        'template_deleted_success': '✅ Template successfully deleted.',
        'yes_button': '✅ Yes',
        'no_button': '❌ No',
        'unassign_ticket_button': '🚫 Unassign',
        'back_to_ticket_detail': '🔙 Back to ticket detail',
        'ticket_not_open_for_edit': '❌ This ticket cannot be edited. It might be closed or already assigned.',
        'ticket_code_not_found': '❌ Ticket with code {code} not found.',
        'not_your_ticket': '❌ This is not your ticket.',
        'role_user': 'User',
        'role_admin': 'Admin',
        'role_moderator': 'Moderator',
        'role_superadmin': 'Superadmin',
        'admin_menu_title': '⚙️ Admin Panel',
        'moderator_menu_title': '⚙️ Moderator Panel',
        'superadmin_menu_title': '👑 Superadmin Panel',
        'admin_panel_button': '⚙️ Admin Panel',
        'moderator_panel_button': '⚙️ Moderator Panel',
        'superadmin_panel_button': '👑 Superadmin Panel',
        'language_button': '🌐 Language',
        'manage_users_title': '👥 Manage Users',
        'no_users_registered': '❌ No registered users found.',
        'set_role_for_user': 'Set role for {user_display}:',
        'role_updated_success': '✅ User {user_display} role updated to "{role}".',
        'assign_ticket_button': '👤 Assign',
        'send_template_button': '📝 Send Template',
        'reply_button': '💬 Reply',
        'close_ticket_button': '🔒 Close Ticket',
        'edit_ticket_button': '✏️ Edit',
        'ticket_code_not_found_in_state': 'Error: Ticket code not found in state.',
        'ticket_already_closed': 'ℹ️ Ticket {code} is already closed.',
        'feedback_data_not_found': 'Error: Feedback data not found.',
        'ticket_code_not_found_for_edit': 'Error: Ticket code for editing not found.',
        'export_options_title': '📊 Export Options',
        'export_priority_all': 'All Priorities',
        'export_category_all': 'All Categories',
        'export_assigned_all': 'All Assigned',
        'export_assigned_unassigned': 'Unassigned',
        'export_assigned_me': 'Assigned to Me',
        'export_assigned_specific': 'Assign Specific',
        'export_tickets_button': '✅ Export Tickets',
        'export_enter_dates': 'Enter date in YYYY-MM-DD format (leave empty to clear filter).',
        'select_filter_status': 'Select status for filtering:',
        'select_filter_priority': 'Select priority for filtering:',
        'select_filter_category': 'Select category for filtering:',
        'select_filter_assigned': 'Select assignment for filtering:',
    }
}
